<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;
use App\Models\Category;
use App\Models\Product;
use App\Models\Inventory;
use App\Models\Customer;
use App\Models\Staff;
use App\Models\Quote;
use App\Models\QuoteItem;
use App\Models\Invoice;
use App\Models\InvoiceItem;
use App\Models\Expense;
use App\Models\CustomerLedgerEntry;

class SeedTestData extends Command
{
    protected $signature   = 'bellevue:seed-test';
    protected $description = 'Seed test data: category, product, customer, staff, quote, invoice, expense, ledger';

    public function handle(): int
    {
        $this->info('Seeding test data…');

        // ── 1. CATEGORY ────────────────────────────────────────────────────
        $category = Category::firstOrCreate(
            ['name' => 'Test Electronics'],
            [
                'slug'      => 'test-electronics',
                'is_active' => true,
                'sort_order'=> 99,
            ]
        );
        $this->line("  ✓ Category: {$category->name}");

        // ── 2. PRODUCT ─────────────────────────────────────────────────────
        $product = Product::firstOrCreate(
            ['sku' => 'TEST-001'],
            [
                'category_id'      => $category->id,
                'name'             => 'Test Wireless Headphones',
                'slug'             => 'test-wireless-headphones',
                'description'      => 'High-quality test headphones for demo purposes.',
                'cost'             => 45.00,
                'price'            => 89.99,
                'markup_percentage'=> 100,
                'is_active'        => true,
            ]
        );
        $this->line("  ✓ Product: {$product->name} @ \${$product->price}");

        // Ensure inventory record exists
        Inventory::firstOrCreate(
            ['product_id' => $product->id],
            ['qty_on_hand' => 20, 'reorder_level' => 5]
        );

        // ── 3. CUSTOMER ────────────────────────────────────────────────────
        $customer = Customer::firstOrCreate(
            ['email' => 'testcustomer@bellevuegifts.com'],
            [
                'name'         => 'Test Customer — Jane Doe',
                'phone'        => '2421234567',
                'address'      => '12 Pioneers Way, Freeport',
                'island'       => 'Grand Bahama',
                'account_type' => 'personal',
                'customer_tier'=> 'retail',
            ]
        );
        $this->line("  ✓ Customer: {$customer->name}");

        // ── 4. STAFF ───────────────────────────────────────────────────────
        $staff = Staff::firstOrCreate(
            ['email' => 'teststaff@bellevuegifts.com'],
            [
                'name'      => 'Test Staff — John Smith',
                'role'      => 'cashier',
                'is_active' => true,
            ]
        );
        $this->line("  ✓ Staff: {$staff->name} ({$staff->role})");

        // ── 5. QUOTE ───────────────────────────────────────────────────────
        $quote = Quote::firstOrCreate(
            ['quote_number' => 'QT-TEST-001'],
            [
                'customer_id'    => $customer->id,
                'status'         => 'sent',
                'issued_date'    => now()->toDateString(),
                'valid_until'    => now()->addDays(30)->toDateString(),
                'notes'          => 'Test quote generated by seed command.',
                'subtotal'       => 179.98,
                'tax_total'      => 17.99,
                'discount_total' => 10.00,
                'total'          => 187.97,
            ]
        );

        QuoteItem::firstOrCreate(
            ['quote_id' => $quote->id, 'product_id' => $product->id],
            [
                'description'  => $product->name,
                'quantity'     => 2,
                'unit_price'   => 89.99,
                'tax_percent'  => 10,
                'discount'     => 10.00,
                'line_total'   => 169.98,
            ]
        );
        $this->line("  ✓ Quote: {$quote->quote_number} — \${$quote->total}");

        // ── 6. QUOTE → INVOICE CONVERSION ─────────────────────────────────
        $invoice = Invoice::firstOrCreate(
            ['invoice_number' => 'INV-TEST-001'],
            [
                'customer_id'    => $customer->id,
                'quote_id'       => $quote->id,
                'status'         => 'sent',
                'issued_date'    => now()->toDateString(),
                'due_date'       => now()->addDays(14)->toDateString(),
                'notes'          => 'Converted from ' . $quote->quote_number . '. Test invoice.',
                'subtotal'       => $quote->subtotal,
                'tax_total'      => $quote->tax_total,
                'discount_total' => $quote->discount_total,
                'total'          => $quote->total,
                'amount_paid'    => 100.00,
            ]
        );

        InvoiceItem::firstOrCreate(
            ['invoice_id' => $invoice->id, 'product_id' => $product->id],
            [
                'description' => $product->name,
                'quantity'    => 2,
                'unit_price'  => 89.99,
                'tax_percent' => 10,
                'discount'    => 10.00,
                'line_total'  => 169.98,
            ]
        );

        // Mark quote as accepted now that invoice exists
        $quote->update(['status' => 'accepted']);
        $this->line("  ✓ Invoice: {$invoice->invoice_number} — total \${$invoice->total}, paid \${$invoice->amount_paid}, balance \$" . ($invoice->total - $invoice->amount_paid));

        // ── 7. LEDGER ENTRIES (statement test data) ─────────────────────────
        $existing = CustomerLedgerEntry::where('customer_id', $customer->id)->count();
        if ($existing === 0) {
            $entries = [
                [
                    'entry_type'     => 'charge',
                    'reference_type' => 'invoice',
                    'reference_id'   => $invoice->id,
                    'amount'         => $invoice->total,
                    'balance_after'  => $invoice->total,
                    'notes'          => "Invoice {$invoice->invoice_number} issued",
                    'entry_date'     => now()->subDays(10)->toDateString(),
                ],
                [
                    'entry_type'     => 'payment',
                    'reference_type' => 'invoice',
                    'reference_id'   => $invoice->id,
                    'amount'         => -100.00,
                    'balance_after'  => $invoice->total - 100.00,
                    'notes'          => 'Partial payment received — bank transfer',
                    'entry_date'     => now()->subDays(3)->toDateString(),
                ],
            ];

            foreach ($entries as $entry) {
                CustomerLedgerEntry::create(array_merge($entry, ['customer_id' => $customer->id]));
            }
            $this->line("  ✓ Ledger: 2 entries (charge + partial payment)");
        } else {
            $this->line("  ~ Ledger: {$existing} entries already exist, skipped");
        }

        // ── 8. EXPENSE ─────────────────────────────────────────────────────
        $expense = Expense::firstOrCreate(
            ['title' => 'Test Office Supplies Purchase'],
            [
                'vendor_payee' => 'Office World Bahamas',
                'category'     => 'supplies',
                'amount'       => 125.50,
                'notes'        => 'Pens, paper, printer ink — test entry',
                'date'         => now()->toDateString(),
                'staff_id'     => $staff->id,
            ]
        );
        $this->line("  ✓ Expense: {$expense->title} — \${$expense->amount}");

        $this->newLine();
        $this->info('All test data seeded successfully.');
        $this->newLine();
        $this->line('  Live URLs to test:');
        $this->line('  → https://bellevuegifts.com/admin/customers');
        $this->line('  → https://bellevuegifts.com/admin/quotes');
        $this->line('  → https://bellevuegifts.com/admin/invoices');
        $this->line('  → https://bellevuegifts.com/admin/statements?customer_id=' . $customer->id);
        $this->line('  → https://bellevuegifts.com/admin/expenses');
        $this->line('  → https://bellevuegifts.com/admin/reports');

        return self::SUCCESS;
    }
}
